export enum Animation {
  Rainbow,
  RainbowLinear,
  RainbowCentered,
  GradientLinear,
  GradientCenter,
  Static,
  ColorBarsLinearHard,
  ColorBarsLinearSoft,
  ColorBarsCenterHard,
  ColorBarsCenterSoft,
  RainbowLinearAccX,
  RainbowLinearAccY,
  RainbowCenteredAccX,
  RainbowCenteredAccY,
  GradientLinearAccX,
  GradientLinearAccY,
  GradientCenteredAccX,
  GradientCenteredAccY,
  Custom = 255,
}
