name: PlatformIO Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PlatformIO Build
        uses: TheRealKasumi/TesLight/.github/actions/platformio-build@feat/DevOps_Auto_build_for_Update_Packages
